//Required by background_fetch build
ext {
    compileSdkVersion   = 37
    targetSdkVersion    = 37
    ndkVersion          = providers.gradleProperty("weblibre.ndkVersion").get()
}

allprojects {
    repositories {
        google()
        mavenCentral()
        //Required by background_fetch build
        maven { url "${project(':background_fetch').projectDir}/libs" }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    afterEvaluate {
        if (it.hasProperty("android")) {
            android {
                compileSdkVersion 37
                ndkVersion rootProject.ext.ndkVersion
            }
        }
    }
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
