// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// What a Dart owner must do next with the process profile decision.
enum ProfileStartupDirectiveKind {
  /// A profile is already committed; adopt it and boot.
  committed,

  /// The caller holds a selection lease and must commit or release it.
  select,

  /// The caller holds a maintenance lease and must run recovery or queued work.
  maintenance,

  /// Another owner holds the decision, or the process is terminating. The caller
  /// must never fall back to reading `current_profile` itself.
  unavailable,
}

/// Which kind of Dart owner is asking. Only a UI owner can show a picker.
enum ProfileStartupOwnerType { ui, headless }

/// One step of the participant transaction protocol.
enum ParticipantStep { discover, prepare, apply, verify, finalize, rollback }

/// Mirrors the `profilePrompt` setting in `startup_config.json`.
enum ProfileStartupPromptMode { off, browserOnly }

class ProfileStartupDirective {
  ProfileStartupDirective({
    required this.kind,
    this.profileId,
    this.candidateProfileId,
    this.leaseId,
    required this.showPicker,
    this.maintenanceTaskId,
    required this.recoveryRequired,
    this.reason,
  });

  ProfileStartupDirectiveKind kind;

  /// Set for [ProfileStartupDirectiveKind.committed].
  String? profileId;

  /// The profile the shared candidate rule resolved, for a selection lease.
  String? candidateProfileId;

  /// Fencing token for the granted selection or maintenance lease.
  String? leaseId;

  bool showPicker;

  String? maintenanceTaskId;

  bool recoveryRequired;

  /// Why the decision is unavailable, or which restart the caller must schedule.
  String? reason;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      profileId,
      candidateProfileId,
      leaseId,
      showPicker,
      maintenanceTaskId,
      recoveryRequired,
      reason,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ProfileStartupDirective decode(Object result) {
    result as List<Object?>;
    return ProfileStartupDirective(
      kind: result[0]! as ProfileStartupDirectiveKind,
      profileId: result[1] as String?,
      candidateProfileId: result[2] as String?,
      leaseId: result[3] as String?,
      showPicker: result[4]! as bool,
      maintenanceTaskId: result[5] as String?,
      recoveryRequired: result[6]! as bool,
      reason: result[7] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProfileStartupDirective || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) &&
        _deepEquals(profileId, other.profileId) &&
        _deepEquals(candidateProfileId, other.candidateProfileId) &&
        _deepEquals(leaseId, other.leaseId) &&
        _deepEquals(showPicker, other.showPicker) &&
        _deepEquals(maintenanceTaskId, other.maintenanceTaskId) &&
        _deepEquals(recoveryRequired, other.recoveryRequired) &&
        _deepEquals(reason, other.reason);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ProfileStartupDirective(kind: $kind, profileId: $profileId, candidateProfileId: $candidateProfileId, leaseId: $leaseId, showPicker: $showPicker, maintenanceTaskId: $maintenanceTaskId, recoveryRequired: $recoveryRequired, reason: $reason)';
  }
}

/// Profile arbitration, registered at plugin attach time so it is callable
/// before anything opens a database or initializes Gecko.
/// One launch the broker is holding because nothing could receive it.
///
/// Only what survives a process restart unchanged: arbitrary `Parcelable` extras
/// have no such representation, and a best-effort rendering of one is worse than
/// its absence because the consumer cannot tell the two apart.
class StartupIntentRecord {
  StartupIntentRecord({
    required this.id,
    required this.sequence,
    this.action,
    this.dataUri,
    this.mimeType,
    required this.categories,
    required this.extras,
    this.trustedProfileId,
    this.callerPackage,
  });

  String id;

  int sequence;

  String? action;

  String? dataUri;

  String? mimeType;

  List<String> categories;

  Map<String, Object?> extras;

  String? trustedProfileId;

  /// The app that sent the launch, as native resolved it when it arrived.
  ///
  /// Carried across the queue because it cannot be recovered afterwards:
  /// `getReferrer()` answers about the activity running when it is asked, which
  /// at replay time is this app. Null means internal or unestablished, exactly as
  /// it does on a live intent — the gatekeeper reads it the same way in both.
  String? callerPackage;

  List<Object?> _toList() {
    return <Object?>[
      id,
      sequence,
      action,
      dataUri,
      mimeType,
      categories,
      extras,
      trustedProfileId,
      callerPackage,
    ];
  }

  Object encode() {
    return _toList();
  }

  static StartupIntentRecord decode(Object result) {
    result as List<Object?>;
    return StartupIntentRecord(
      id: result[0]! as String,
      sequence: result[1]! as int,
      action: result[2] as String?,
      dataUri: result[3] as String?,
      mimeType: result[4] as String?,
      categories: (result[5]! as List<Object?>).cast<String>(),
      extras: (result[6]! as Map<Object?, Object?>).cast<String, Object?>(),
      trustedProfileId: result[7] as String?,
      callerPackage: result[8] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StartupIntentRecord || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(sequence, other.sequence) &&
        _deepEquals(action, other.action) &&
        _deepEquals(dataUri, other.dataUri) &&
        _deepEquals(mimeType, other.mimeType) &&
        _deepEquals(categories, other.categories) &&
        _deepEquals(extras, other.extras) &&
        _deepEquals(trustedProfileId, other.trustedProfileId) &&
        _deepEquals(callerPackage, other.callerPackage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'StartupIntentRecord(id: $id, sequence: $sequence, action: $action, dataUri: $dataUri, mimeType: $mimeType, categories: $categories, extras: $extras, trustedProfileId: $trustedProfileId, callerPackage: $callerPackage)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is ProfileStartupDirectiveKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is ProfileStartupOwnerType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is ParticipantStep) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is ProfileStartupPromptMode) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is ProfileStartupDirective) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is StartupIntentRecord) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ProfileStartupDirectiveKind.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : ProfileStartupOwnerType.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : ParticipantStep.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : ProfileStartupPromptMode.values[value];
      case 133:
        return ProfileStartupDirective.decode(readValue(buffer)!);
      case 134:
        return StartupIntentRecord.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class GeckoProfileApi {
  /// Constructor for [GeckoProfileApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  GeckoProfileApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<ProfileStartupDirective> beginStartup(
    ProfileStartupOwnerType ownerType,
    String engineId,
    ProfileStartupPromptMode promptMode,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.beginStartup$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[ownerType, engineId, promptMode],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as ProfileStartupDirective;
  }

  /// Commits the profile chosen under [leaseId]. Returns false for a stale lease
  /// or a profile that no longer validates; the caller must not proceed.
  Future<bool> commitSelection(String leaseId, String profileId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.commitSelection$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[leaseId, profileId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> heartbeatSelection(String leaseId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.heartbeatSelection$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[leaseId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> releaseSelection(String leaseId, String reason) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.releaseSelection$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[leaseId, reason],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> heartbeatMaintenance(String leaseId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.heartbeatMaintenance$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[leaseId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Holds or releases the maintenance deadline.
  ///
  /// Held means "this owner is not running": the maintenance UI is not resumed,
  /// so Android may freeze the process, and a frozen isolate fires no timers.
  /// Without it the deadline measures how long the platform declined to run the
  /// owner, and an ordinary trip to a password manager can expire the lease.
  /// Any heartbeat or boundary assertion releases it again.
  Future<bool> holdMaintenanceHeartbeat(String leaseId, bool held) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.holdMaintenanceHeartbeat$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[leaseId, held],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// The fencing check every destructive maintenance boundary must pass.
  Future<bool> assertMaintenanceLease(
    String leaseId,
    String? taskId,
    String boundary,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.assertMaintenanceLease$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[leaseId, taskId, boundary],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> suspendMaintenance(String leaseId, String? taskId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.suspendMaintenance$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[leaseId, taskId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> finishMaintenance(String leaseId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.finishMaintenance$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[leaseId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Arms a durable restart, optionally targeting another profile.
  ///
  /// Returns false having changed nothing observable, so a caller that gets false
  /// can report the failure and keep running. On true the process is terminal and
  /// must call [completeProfileRestart] once teardown is done.
  Future<bool> armProfileRestart(String? targetProfileId, String reason) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.armProfileRestart$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[targetProfileId, reason],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Tears down and exits. Never returns.
  Future<void> completeProfileRestart() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.completeProfileRestart$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Ids of the native maintenance participants this build registers.
  ///
  /// Dart orchestrates them; native owns what each one actually touches. An
  /// empty list means a directory-scoped operation is all this build can do.
  Future<List<String>> listMaintenanceParticipants() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.listMaintenanceParticipants$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  /// Runs one participant step. Returns false when the step refused; the caller
  /// treats that as a failure of the participant, not of the channel.
  Future<bool> runMaintenanceParticipantStep(
    String participantId,
    ParticipantStep step,
    String taskId,
    String profileId,
    String journalKind,
    String workDirPath,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.runMaintenanceParticipantStep$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[
        participantId,
        step,
        taskId,
        profileId,
        journalKind,
        workDirPath,
      ],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Free bytes on the filesystem holding [path], or null when it cannot be
  /// determined. Used for backup preflight, so an unknown answer must not be
  /// reported as zero.
  Future<int?> getAvailableBytes(String path) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.getAvailableBytes$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[path],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as int?;
  }

  /// Flushes a *directory's* own metadata to disk.
  ///
  /// Dart can fsync a file but not a directory, and a rename is recorded in the
  /// parent directory rather than in either file. So a journal phase written and
  /// flushed can still be lost if the machine dies before the directory entry
  /// reaches the platter — the exact window §11.5's recovery is written to
  /// tolerate. This narrows it instead of relying on tolerating it.
  ///
  /// Returns false when the directory could not be opened or synced; callers
  /// treat that as "the window is still open", never as a failure of the
  /// operation.
  Future<bool> syncDirectory(String path) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.syncDirectory$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[path],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Claims the right for this Dart isolate to hold profile state open.
  ///
  /// Returns false when another isolate holds it; the caller retries or gives
  /// up, and never opens a database anyway.
  Future<bool> claimProfileAccess(
    ProfileStartupOwnerType ownerType,
    String engineId,
    String? taskId,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.claimProfileAccess$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[ownerType, engineId, taskId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> releaseProfileAccess(
    ProfileStartupOwnerType ownerType,
    String engineId,
    String? taskId,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.releaseProfileAccess$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[ownerType, engineId, taskId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Claims every queued launch this engine may deliver, oldest first.
  ///
  /// Claiming and reading are one call because they have to be: a reader that
  /// looked first and claimed afterwards would let a second engine read the same
  /// entry in between.
  Future<List<StartupIntentRecord>> claimStartupIntents(String engineId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.claimStartupIntents$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[engineId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<StartupIntentRecord>();
  }

  /// Marks a queued launch delivered, so it is never replayed.
  Future<bool> acknowledgeStartupIntent(String entryId, String engineId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.acknowledgeStartupIntent$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[entryId, engineId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Hands a claimed launch back undelivered, for another engine or another run.
  Future<bool> releaseStartupIntent(String entryId, String engineId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.releaseStartupIntent$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[entryId, engineId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<String?> getCommittedProfileId() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.getCommittedProfileId$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<String?> getBoundProfileFolder() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.getBoundProfileFolder$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }
}
