// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package eu.weblibre.flutter_mozilla_components.pigeons

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object StartupPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is StartupFlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class StartupFlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** What a Dart owner must do next with the process profile decision. */
enum class ProfileStartupDirectiveKind(val raw: Int) {
  /** A profile is already committed; adopt it and boot. */
  COMMITTED(0),
  /** The caller holds a selection lease and must commit or release it. */
  SELECT(1),
  /** The caller holds a maintenance lease and must run recovery or queued work. */
  MAINTENANCE(2),
  /**
   * Another owner holds the decision, or the process is terminating. The caller
   * must never fall back to reading `current_profile` itself.
   */
  UNAVAILABLE(3);

  companion object {
    fun ofRaw(raw: Int): ProfileStartupDirectiveKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Which kind of Dart owner is asking. Only a UI owner can show a picker. */
enum class ProfileStartupOwnerType(val raw: Int) {
  UI(0),
  HEADLESS(1);

  companion object {
    fun ofRaw(raw: Int): ProfileStartupOwnerType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** One step of the participant transaction protocol. */
enum class ParticipantStep(val raw: Int) {
  DISCOVER(0),
  PREPARE(1),
  APPLY(2),
  VERIFY(3),
  FINALIZE(4),
  ROLLBACK(5);

  companion object {
    fun ofRaw(raw: Int): ParticipantStep? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Mirrors the `profilePrompt` setting in `startup_config.json`. */
enum class ProfileStartupPromptMode(val raw: Int) {
  OFF(0),
  BROWSER_ONLY(1);

  companion object {
    fun ofRaw(raw: Int): ProfileStartupPromptMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProfileStartupDirective (
  val kind: ProfileStartupDirectiveKind,
  /** Set for [ProfileStartupDirectiveKind.committed]. */
  val profileId: String? = null,
  /** The profile the shared candidate rule resolved, for a selection lease. */
  val candidateProfileId: String? = null,
  /** Fencing token for the granted selection or maintenance lease. */
  val leaseId: String? = null,
  val showPicker: Boolean,
  val maintenanceTaskId: String? = null,
  val recoveryRequired: Boolean,
  /** Why the decision is unavailable, or which restart the caller must schedule. */
  val reason: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProfileStartupDirective {
      val kind = pigeonVar_list[0] as ProfileStartupDirectiveKind
      val profileId = pigeonVar_list[1] as String?
      val candidateProfileId = pigeonVar_list[2] as String?
      val leaseId = pigeonVar_list[3] as String?
      val showPicker = pigeonVar_list[4] as Boolean
      val maintenanceTaskId = pigeonVar_list[5] as String?
      val recoveryRequired = pigeonVar_list[6] as Boolean
      val reason = pigeonVar_list[7] as String?
      return ProfileStartupDirective(kind, profileId, candidateProfileId, leaseId, showPicker, maintenanceTaskId, recoveryRequired, reason)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      profileId,
      candidateProfileId,
      leaseId,
      showPicker,
      maintenanceTaskId,
      recoveryRequired,
      reason,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProfileStartupDirective
    return StartupPigeonUtils.deepEquals(this.kind, other.kind) && StartupPigeonUtils.deepEquals(this.profileId, other.profileId) && StartupPigeonUtils.deepEquals(this.candidateProfileId, other.candidateProfileId) && StartupPigeonUtils.deepEquals(this.leaseId, other.leaseId) && StartupPigeonUtils.deepEquals(this.showPicker, other.showPicker) && StartupPigeonUtils.deepEquals(this.maintenanceTaskId, other.maintenanceTaskId) && StartupPigeonUtils.deepEquals(this.recoveryRequired, other.recoveryRequired) && StartupPigeonUtils.deepEquals(this.reason, other.reason)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StartupPigeonUtils.deepHash(this.kind)
    result = 31 * result + StartupPigeonUtils.deepHash(this.profileId)
    result = 31 * result + StartupPigeonUtils.deepHash(this.candidateProfileId)
    result = 31 * result + StartupPigeonUtils.deepHash(this.leaseId)
    result = 31 * result + StartupPigeonUtils.deepHash(this.showPicker)
    result = 31 * result + StartupPigeonUtils.deepHash(this.maintenanceTaskId)
    result = 31 * result + StartupPigeonUtils.deepHash(this.recoveryRequired)
    result = 31 * result + StartupPigeonUtils.deepHash(this.reason)
    return result
  }
  override fun toString(): String {
    return "ProfileStartupDirective(kind=$kind, profileId=$profileId, candidateProfileId=$candidateProfileId, leaseId=$leaseId, showPicker=$showPicker, maintenanceTaskId=$maintenanceTaskId, recoveryRequired=$recoveryRequired, reason=$reason)"
  }
}

/**
 * Profile arbitration, registered at plugin attach time so it is callable
 * before anything opens a database or initializes Gecko.
 * One launch the broker is holding because nothing could receive it.
 *
 * Only what survives a process restart unchanged: arbitrary `Parcelable` extras
 * have no such representation, and a best-effort rendering of one is worse than
 * its absence because the consumer cannot tell the two apart.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StartupIntentRecord (
  val id: String,
  val sequence: Long,
  val action: String? = null,
  val dataUri: String? = null,
  val mimeType: String? = null,
  val categories: List<String>,
  val extras: Map<String, Any?>,
  val trustedProfileId: String? = null,
  /**
   * The app that sent the launch, as native resolved it when it arrived.
   *
   * Carried across the queue because it cannot be recovered afterwards:
   * `getReferrer()` answers about the activity running when it is asked, which
   * at replay time is this app. Null means internal or unestablished, exactly as
   * it does on a live intent — the gatekeeper reads it the same way in both.
   */
  val callerPackage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StartupIntentRecord {
      val id = pigeonVar_list[0] as String
      val sequence = pigeonVar_list[1] as Long
      val action = pigeonVar_list[2] as String?
      val dataUri = pigeonVar_list[3] as String?
      val mimeType = pigeonVar_list[4] as String?
      val categories = pigeonVar_list[5] as List<String>
      val extras = pigeonVar_list[6] as Map<String, Any?>
      val trustedProfileId = pigeonVar_list[7] as String?
      val callerPackage = pigeonVar_list[8] as String?
      return StartupIntentRecord(id, sequence, action, dataUri, mimeType, categories, extras, trustedProfileId, callerPackage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      sequence,
      action,
      dataUri,
      mimeType,
      categories,
      extras,
      trustedProfileId,
      callerPackage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StartupIntentRecord
    return StartupPigeonUtils.deepEquals(this.id, other.id) && StartupPigeonUtils.deepEquals(this.sequence, other.sequence) && StartupPigeonUtils.deepEquals(this.action, other.action) && StartupPigeonUtils.deepEquals(this.dataUri, other.dataUri) && StartupPigeonUtils.deepEquals(this.mimeType, other.mimeType) && StartupPigeonUtils.deepEquals(this.categories, other.categories) && StartupPigeonUtils.deepEquals(this.extras, other.extras) && StartupPigeonUtils.deepEquals(this.trustedProfileId, other.trustedProfileId) && StartupPigeonUtils.deepEquals(this.callerPackage, other.callerPackage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StartupPigeonUtils.deepHash(this.id)
    result = 31 * result + StartupPigeonUtils.deepHash(this.sequence)
    result = 31 * result + StartupPigeonUtils.deepHash(this.action)
    result = 31 * result + StartupPigeonUtils.deepHash(this.dataUri)
    result = 31 * result + StartupPigeonUtils.deepHash(this.mimeType)
    result = 31 * result + StartupPigeonUtils.deepHash(this.categories)
    result = 31 * result + StartupPigeonUtils.deepHash(this.extras)
    result = 31 * result + StartupPigeonUtils.deepHash(this.trustedProfileId)
    result = 31 * result + StartupPigeonUtils.deepHash(this.callerPackage)
    return result
  }
  override fun toString(): String {
    return "StartupIntentRecord(id=$id, sequence=$sequence, action=$action, dataUri=$dataUri, mimeType=$mimeType, categories=$categories, extras=$extras, trustedProfileId=$trustedProfileId, callerPackage=$callerPackage)"
  }
}
private open class StartupPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ProfileStartupDirectiveKind.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ProfileStartupOwnerType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ParticipantStep.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ProfileStartupPromptMode.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProfileStartupDirective.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StartupIntentRecord.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ProfileStartupDirectiveKind -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ProfileStartupOwnerType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is ParticipantStep -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is ProfileStartupPromptMode -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is ProfileStartupDirective -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is StartupIntentRecord -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface GeckoProfileApi {
  fun beginStartup(ownerType: ProfileStartupOwnerType, engineId: String, promptMode: ProfileStartupPromptMode): ProfileStartupDirective
  /**
   * Commits the profile chosen under [leaseId]. Returns false for a stale lease
   * or a profile that no longer validates; the caller must not proceed.
   */
  fun commitSelection(leaseId: String, profileId: String): Boolean
  fun heartbeatSelection(leaseId: String): Boolean
  fun releaseSelection(leaseId: String, reason: String): Boolean
  fun heartbeatMaintenance(leaseId: String): Boolean
  /**
   * Holds or releases the maintenance deadline.
   *
   * Held means "this owner is not running": the maintenance UI is not resumed,
   * so Android may freeze the process, and a frozen isolate fires no timers.
   * Without it the deadline measures how long the platform declined to run the
   * owner, and an ordinary trip to a password manager can expire the lease.
   * Any heartbeat or boundary assertion releases it again.
   */
  fun holdMaintenanceHeartbeat(leaseId: String, held: Boolean): Boolean
  /** The fencing check every destructive maintenance boundary must pass. */
  fun assertMaintenanceLease(leaseId: String, taskId: String?, boundary: String): Boolean
  fun suspendMaintenance(leaseId: String, taskId: String?): Boolean
  fun finishMaintenance(leaseId: String): Boolean
  /**
   * Arms a durable restart, optionally targeting another profile.
   *
   * Returns false having changed nothing observable, so a caller that gets false
   * can report the failure and keep running. On true the process is terminal and
   * must call [completeProfileRestart] once teardown is done.
   */
  fun armProfileRestart(targetProfileId: String?, reason: String): Boolean
  /** Tears down and exits. Never returns. */
  fun completeProfileRestart()
  /**
   * Ids of the native maintenance participants this build registers.
   *
   * Dart orchestrates them; native owns what each one actually touches. An
   * empty list means a directory-scoped operation is all this build can do.
   */
  fun listMaintenanceParticipants(): List<String>
  /**
   * Runs one participant step. Returns false when the step refused; the caller
   * treats that as a failure of the participant, not of the channel.
   */
  fun runMaintenanceParticipantStep(participantId: String, step: ParticipantStep, taskId: String, profileId: String, journalKind: String, workDirPath: String): Boolean
  /**
   * Free bytes on the filesystem holding [path], or null when it cannot be
   * determined. Used for backup preflight, so an unknown answer must not be
   * reported as zero.
   */
  fun getAvailableBytes(path: String): Long?
  /**
   * Flushes a *directory's* own metadata to disk.
   *
   * Dart can fsync a file but not a directory, and a rename is recorded in the
   * parent directory rather than in either file. So a journal phase written and
   * flushed can still be lost if the machine dies before the directory entry
   * reaches the platter — the exact window §11.5's recovery is written to
   * tolerate. This narrows it instead of relying on tolerating it.
   *
   * Returns false when the directory could not be opened or synced; callers
   * treat that as "the window is still open", never as a failure of the
   * operation.
   */
  fun syncDirectory(path: String): Boolean
  /**
   * Claims the right for this Dart isolate to hold profile state open.
   *
   * Returns false when another isolate holds it; the caller retries or gives
   * up, and never opens a database anyway.
   */
  fun claimProfileAccess(ownerType: ProfileStartupOwnerType, engineId: String, taskId: String?): Boolean
  fun releaseProfileAccess(ownerType: ProfileStartupOwnerType, engineId: String, taskId: String?): Boolean
  /**
   * Claims every queued launch this engine may deliver, oldest first.
   *
   * Claiming and reading are one call because they have to be: a reader that
   * looked first and claimed afterwards would let a second engine read the same
   * entry in between.
   */
  fun claimStartupIntents(engineId: String): List<StartupIntentRecord>
  /** Marks a queued launch delivered, so it is never replayed. */
  fun acknowledgeStartupIntent(entryId: String, engineId: String): Boolean
  /** Hands a claimed launch back undelivered, for another engine or another run. */
  fun releaseStartupIntent(entryId: String, engineId: String): Boolean
  fun getCommittedProfileId(): String?
  fun getBoundProfileFolder(): String?

  companion object {
    /** The codec used by GeckoProfileApi. */
    val codec: MessageCodec<Any?> by lazy {
      StartupPigeonCodec()
    }
    /** Sets up an instance of `GeckoProfileApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: GeckoProfileApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.beginStartup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val ownerTypeArg = args[0] as ProfileStartupOwnerType
            val engineIdArg = args[1] as String
            val promptModeArg = args[2] as ProfileStartupPromptMode
            val wrapped: List<Any?> = try {
              listOf(api.beginStartup(ownerTypeArg, engineIdArg, promptModeArg))
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.commitSelection$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val leaseIdArg = args[0] as String
            val profileIdArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.commitSelection(leaseIdArg, profileIdArg))
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.heartbeatSelection$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val leaseIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.heartbeatSelection(leaseIdArg))
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.releaseSelection$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val leaseIdArg = args[0] as String
            val reasonArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.releaseSelection(leaseIdArg, reasonArg))
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.heartbeatMaintenance$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val leaseIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.heartbeatMaintenance(leaseIdArg))
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.holdMaintenanceHeartbeat$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val leaseIdArg = args[0] as String
            val heldArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              listOf(api.holdMaintenanceHeartbeat(leaseIdArg, heldArg))
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.assertMaintenanceLease$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val leaseIdArg = args[0] as String
            val taskIdArg = args[1] as String?
            val boundaryArg = args[2] as String
            val wrapped: List<Any?> = try {
              listOf(api.assertMaintenanceLease(leaseIdArg, taskIdArg, boundaryArg))
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.suspendMaintenance$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val leaseIdArg = args[0] as String
            val taskIdArg = args[1] as String?
            val wrapped: List<Any?> = try {
              listOf(api.suspendMaintenance(leaseIdArg, taskIdArg))
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.finishMaintenance$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val leaseIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.finishMaintenance(leaseIdArg))
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.armProfileRestart$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val targetProfileIdArg = args[0] as String?
            val reasonArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.armProfileRestart(targetProfileIdArg, reasonArg))
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.completeProfileRestart$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.completeProfileRestart()
              listOf(null)
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.listMaintenanceParticipants$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.listMaintenanceParticipants())
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.runMaintenanceParticipantStep$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val participantIdArg = args[0] as String
            val stepArg = args[1] as ParticipantStep
            val taskIdArg = args[2] as String
            val profileIdArg = args[3] as String
            val journalKindArg = args[4] as String
            val workDirPathArg = args[5] as String
            val wrapped: List<Any?> = try {
              listOf(api.runMaintenanceParticipantStep(participantIdArg, stepArg, taskIdArg, profileIdArg, journalKindArg, workDirPathArg))
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.getAvailableBytes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getAvailableBytes(pathArg))
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.syncDirectory$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.syncDirectory(pathArg))
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.claimProfileAccess$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val ownerTypeArg = args[0] as ProfileStartupOwnerType
            val engineIdArg = args[1] as String
            val taskIdArg = args[2] as String?
            val wrapped: List<Any?> = try {
              listOf(api.claimProfileAccess(ownerTypeArg, engineIdArg, taskIdArg))
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.releaseProfileAccess$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val ownerTypeArg = args[0] as ProfileStartupOwnerType
            val engineIdArg = args[1] as String
            val taskIdArg = args[2] as String?
            val wrapped: List<Any?> = try {
              listOf(api.releaseProfileAccess(ownerTypeArg, engineIdArg, taskIdArg))
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.claimStartupIntents$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val engineIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.claimStartupIntents(engineIdArg))
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.acknowledgeStartupIntent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val entryIdArg = args[0] as String
            val engineIdArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.acknowledgeStartupIntent(entryIdArg, engineIdArg))
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.releaseStartupIntent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val entryIdArg = args[0] as String
            val engineIdArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.releaseStartupIntent(entryIdArg, engineIdArg))
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.getCommittedProfileId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCommittedProfileId())
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_mozilla_components.GeckoProfileApi.getBoundProfileFolder$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getBoundProfileFolder())
            } catch (exception: Throwable) {
              StartupPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
